In [16]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці.
import numpy as np

A = np.random.randint(1, 6, (3, 3))
B = np.random.randint(1, 6, (3, 3))

print("Матриця A:")
print(A)

print("\nМатриця B:")
print(B)

diagonal_product = np.prod(np.diag(B))

print("\nДобуток елементів діагоналі матриці B:", diagonal_product)

Матриця A:
[[5 2 4]
 [4 2 4]
 [4 2 5]]

Матриця B:
[[2 5 1]
 [5 1 1]
 [2 3 2]]

Добуток елементів діагоналі матриці B: 4
