In [12]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 7 та знайдіть її обернену матрицю.
import numpy as np

A = np.random.randint(1, 8, (3, 3))

print("Матриця A:")
print(A)

inverse_A = np.linalg.inv(A)

print("\nОбернена матриця A:")
print(inverse_A)

Матриця A:
[[1 7 7]
 [2 4 6]
 [4 7 2]]

Обернена матриця A:
[[-0.36956522  0.38043478  0.15217391]
 [ 0.2173913  -0.2826087   0.08695652]
 [-0.02173913  0.22826087 -0.10869565]]
