In [13]:
#Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
#від 0 до 1 та транспонуйте її.
import numpy as np

matrix = np.random.randint(0, 2, (4, 4))

print("Оригінальна матриця:")
print(matrix)

transposed = matrix.T

print("\nТранспонована матриця:")
print(transposed)

Оригінальна матриця:
[[0 1 0 1]
 [0 1 0 1]
 [1 0 0 0]
 [0 1 0 1]]

Транспонована матриця:
[[0 0 1 0]
 [1 1 0 1]
 [0 0 0 0]
 [1 1 0 1]]
