In [8]:
#Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 4 та перемножте їх між собою.
import numpy as np

A = np.random.randint(1, 5, (2, 3))

B = np.random.randint(1, 5, (3, 3))

print("Матриця A (2x3):")
print(A)

print("\nМатриця B (3x3):")
print(B)

result = np.dot(A, B)

print("\nДобуток A * B (результат 2x3):")
print(result)

Матриця A (2x3):
[[2 3 3]
 [3 2 4]]

Матриця B (3x3):
[[1 1 4]
 [4 1 4]
 [2 4 3]]

Добуток A * B (результат 2x3):
[[20 17 29]
 [19 21 32]]
