In [18]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 10 та знайдіть найменший елемент матриці.
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))

print("Матриця:")
print(matrix)

min_value = np.min(matrix)

print("\nНайменший елемент матриці:", min_value)

Матриця:
[[2 7 5]
 [2 8 2]
 [2 3 8]]

Найменший елемент матриці: 2
