In [15]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
#випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.random((2, 3))

vector = np.random.random((3, 1))

print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

result = np.dot(matrix, vector)

print("\nДобуток матриці на вектор (результат 2x1):")
print(result)

Матриця 2x3:
[[0.54389975 0.79163315 0.10206811]
 [0.3606912  0.32085248 0.24666564]]

Вектор 3x1:
[[0.69275062]
 [0.06908478]
 [0.57826825]]

Добуток матриці на вектор (результат 2x1):
[[0.49049944]
 [0.41467398]]
