In [4]:
#Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
#1 до 100 та виведіть мін значення
import numpy as np

matrix = np.random.randint(1, 101, (3, 3))

print("Матриця:")
print(matrix)

min_value = np.min(matrix)

print("Мінімальне значення:", min_value)

Матриця:
[[23 61 75]
 [14 75 21]
 [ 4 71 72]]
Мінімальне значення: 4
