In [7]:
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1  до 20 та
#знайдіть їх добуток.
import numpy as np

A = np.random.randint(1, 21, (3, 3))
B = np.random.randint(1, 21, (3, 3))

print("Матриця A:")
print(A)

print("\nМатриця B:")
print(B)

product = np.dot(A, B)

print("\nДобуток A * B:")
print(product)

Матриця A:
[[15 19 13]
 [19 20  4]
 [19 10  8]]

Матриця B:
[[11 15 18]
 [ 7 14 20]
 [11  5 13]]

Добуток A * B:
[[441 556 819]
 [393 585 794]
 [367 465 646]]
