In [17]:
#Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 5 та знайдіть різницю їх елементів.
import numpy as np

A = np.random.randint(1, 6, (4, 4))
B = np.random.randint(1, 6, (4, 4))

print("Матриця A:")
print(A)

print("\nМатриця B:")
print(B)

difference = A - B

print("\nРізниця елементів матриць (A - B):")
print(difference)

Матриця A:
[[5 3 3 1]
 [2 1 3 4]
 [5 2 1 5]
 [5 4 5 4]]

Матриця B:
[[2 4 2 4]
 [2 2 3 4]
 [2 1 3 3]
 [1 2 3 5]]

Різниця елементів матриць (A - B):
[[ 3 -1  1 -3]
 [ 0 -1  0  0]
 [ 3  1 -2  2]
 [ 4  2  2 -1]]
