In [20]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
#діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
#елементів в кожному рядку матриці.
import numpy as np

matrix = np.random.uniform(-2, 2, (3, 3))

print("Матриця:")
print(matrix)

nonzero_counts = np.count_nonzero(matrix, axis=1).reshape(3, 1)

print("\nВектор-стовпчик з кількістю ненульових елементів у кожному рядку:")
print(nonzero_counts)

Матриця:
[[-1.17487837  0.27544752  1.13163133]
 [ 0.50986234 -1.39810273  1.23177306]
 [ 1.89438732  0.41643391 -1.61308909]]

Вектор-стовпчик з кількістю ненульових елементів у кожному рядку:
[[3]
 [3]
 [3]]
