In [5]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
#діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.
import numpy as np

matrix = np.random.random((4, 4))

print("Матриця:")
print(matrix)

count = np.sum(matrix > 0.5)

print("Кількість елементів > 0.5:", count)

Матриця:
[[0.60395389 0.04313906 0.41648436 0.10264353]
 [0.28916072 0.3349407  0.05370057 0.05150687]
 [0.57986091 0.50595392 0.74706267 0.90087084]
 [0.88672105 0.27512831 0.39068494 0.93641187]]
Кількість елементів > 0.5: 7
