In [14]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
#випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
#від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

matrix = np.random.random((3, 4))

vector = np.random.random((4, 1))

print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

result = np.dot(matrix, vector)

print("\nДобуток матриці на вектор:")
print(result)

Матриця 3x4:
[[0.52265798 0.54269319 0.62043287 0.0266842 ]
 [0.23663028 0.48164703 0.47075846 0.20127869]
 [0.42840768 0.67283417 0.70973236 0.66373815]]

Вектор 4x1:
[[0.66471791]
 [0.75268708]
 [0.57425712]
 [0.98571181]]

Добуток матриці на вектор:
[[1.13848919]
 [0.98856105]
 [1.85302724]]
